### ISSUE TITLE
Setup multiple servers with different hostnames (use something like: curl --resolve example.com:80:127.0.0.1  http://example.com/). (OPEN)

### ISSUE THREAD

**Issue by dvargas1** [NGINXcellent/webserv#101]

**Comment by Leofariasrj25** [comment]
This feature is done and working
but there's a caveat, by default port 80 is blocked for processes without privileges and it's way out of the scope of the project
so to make the curl command work you have to use the port

example:

`curl --resolve hey.42.fr:8181:127.0.0.1 http://hey.42.fr:8181`

```
<html>
    <head>
        <title>Hello WebServ World</title>
    </head>
    <body>
        <h2>Have a NGINXexcellent day\n</h2>
    </body>
</html>
```
