### ISSUE TITLE
Configuration file parsing [prototype]

### ISSUE THREAD

**Issue by Leofariasrj25** [NGINXcellent/webserv#18]
One of project's requirements is the webserv executable should accept a configuration file.

this issue has the sole focus on just creating a barebones logic that will parse a txt file containing the configs we need.
using nginx as the basis for our config file, our config file should have the following structure:

```bash
server {
   port 80;
   server-name www.42.rio;
   root /var/www/html;
}
```

again, this is just the barebones to have a server running.

**Comment by dvargas1** [comment]
https://www.nginx.com/resources/wiki/start/topics/examples/full/

**Comment by dvargas1** [comment]
Instantiate the class InputHandler.
I pass [AV1] into it, which will run "checkConfFile" in its constructor to populate the server array.

In checkConfFile:
- I start the fileStream that will go through all the functions.
- I go through the document looking for the word 'server.'
- When I find it, I create a new connection with newServerCheck.
    -newServerCheck will traverse the server between { } looking for keywords and using specific functions to extract the contents. In our server, lines need to end with ; to be extracted.
    -When it finds the word "location," it enters a special function to populate the location configuration structure and add it to the locations array.
- At the end of the function, we will have a filled server array.
- I created methods to print this filled array as a debugging method.
- I handled some specific error cases, such as duplicate entries.

TO DO:

- Add the structures and checks for CGI, which I am not sure about.
- Create Tests 
- Implement more checking

**Comment by dvargas1** [comment]
Created Some tests, in the future we should add more tests.
