### ISSUE TITLE
Building the controller/multiplexer

### ISSUE THREAD

**Issue by Leofariasrj25** [NGINXcellent/webserv#25]
Using the work already done in `TCPServerSocket`, the basic HTTP  implementation and the configuration file, the next milestone is to be able to serve multiple sites at the same time, everything should behave in a non-blocking way.

The Controller will be the Entity that will use the information loaded by the InputHandler and instatiate multiple Server instances (every instance has all the info necessary to handle HTTP requests and responses), The Controller's other  job is to handle the states of all sockets and their respective connections.

This will be the main focus for the project in the upcoming week. most of the others functionality we want to implement, like post for example, needs this to be ironed out.

**Comment by dvargas1** [comment]
LEEEEESGOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
