### ISSUE TITLE
Implement DELETE

### ISSUE THREAD

**Issue by Leofariasrj25** [NGINXcellent/webserv#29]
From the wikipedia:

> DELETE
>     -  The DELETE method requests that the target resource delete its state.

(lol)

Still there are some caveats to handle like the requested resource not existing, no permissions, the method not being acceptable, etc

**Comment by Leofariasrj25** [comment]
@dvargas1 I'm giving this one to you so you can have a feel on how to implement a http method.
You can put it on your backlog, don't focus on it right now.

**Comment by dvargas1** [comment]
> @dvargas1 I'm giving this one to you so you can have a feel on how to implement a http method. You can put it on your backlog, don't focus on it right now.

XACUMIGO
