### ISSUE TITLE
Move file opening logic to epoll

### ISSUE THREAD

**Issue by Leofariasrj25** [NGINXcellent/webserv#58]
at this moment when doing file reading operation for get we're doing this by using FileOpener, a wrapper around ifstream, which is bad because we're opening the file in a blocking way.

to open it a non-blocking way we need `open` and the `O_NONBLOCK` flag, the standard way to read files is to check errno which is prohibited by the pdf.

To accomodate this requiremement we'll change the epoll queue to not only deal with the sockets but with 'regular' file descriptors

**Comment by dvargas1** [comment]
We chose to continue with epoll, adding a new reading logic for the necessary file descriptors.
